apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    projet: tp_deploy
    type: deploy-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bilbloke/backend:1.0
        ports:
        - containerPort: 80
