apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    projet: tp_deploy
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111