apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    projet: tp_deploy
    type: deploy-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bilbloke/frontend:1.0
        ports:
        - containerPort: 80