apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
    projet: tp_deploy
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111