apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: tp_secret
spec:
  containers:
  - image: mariadb:10.3
    name: bdd
    env:
      - name: MYSQL_ROOT_PASSWORD
        #value: kubernetes
        valueFrom:
          secretKeyRef:
            name: demo-secret
            key: db_root_password