apiVersion: v1
kind: Pod
metadata:
  name: mariadb
spec:
  containers:
  - image: mariadb:10.3
    name: bdd
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: demo-secret
            key: db_root_password