apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  labels:
    app: nginx
    projet: npm
data:
  config: |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;

      location ~* \.php$ {
        fastcgi_index   index.php;
        fastcgi_pass    php-service:9000;
        include         fastcgi_params;
        fastcgi_param   SCRIPT_FILENAME    /srv/http$fastcgi_script_name;
        fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
      }
    }