apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    projet: npm
    app: php
spec:
  type: ClusterIP
  selector:
    app: php
    projet: npm
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000